---

- name: Ensure Redis Server is installed
  package:
    name: redis-server
    state: latest

- name: Enable Redis
  service:
    name: redis
    enabled: yes

- name: Write Redis configuration
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: root
    mode: 0644

- name: Restart redis
  service:
    name: redis
    state: restarted

- name: Tune system for Redis
  include: system_tuning.yml
  when: redis_system_tuning
