---

# Fixme: is it possible to make all these changes without restarting PHP-FPM
# multiple times?

- name: Set OpCache shared memory
  ini_file:
    dest: /etc/php/{{php_vers}}/mods-available/opcache.ini
    section: null
    option: opcache.memory_consumption
    value: "{{ phpfpm_opcache_memory_consumption }}"
    state: present
  notify: Restart PHP-FPM

- name: Set OpCache strings buffer
  ini_file:
    dest: /etc/php/{{php_vers}}/mods-available/opcache.ini
    section: null
    option: opcache.interned_strings_buffer
    value: "{{ phpfpm_opcache_interned_strings_buffer }}"
    state: present
  notify: Restart PHP-FPM

- name: Set OpCache file limit
  ini_file:
    dest: /etc/php/{{php_vers}}/mods-available/opcache.ini
    section: null
    option: opcache.max_accelerated_files
    value: "{{ phpfpm_opcache_max_accelerated_files }}"
    state: present
  notify: Restart PHP-FPM
