---

- name: apply common configuration to all nodes
  hosts: all
  become: yes
  vars_files:
    - defaults.yml

  roles:
    - common
    - mariadb
    - redis
    - php-fpm
    - apache-no-varnish
    - wordpress
#    - apache
    - iptables