---

- name: Ensure iptables-persistent package is installed
  package:
    name: iptables-persistent
    state: present

- name: Ensure firewall rules are in place
  template:
    src: "{{ item }}.j2"
    dest: "/etc/iptables/{{ item }}"
    mode: 0600
    owner: root
    group: root
    backup: true
  loop: 
   - rules.v4
   - rules.v6
  notify:  Activate iptables and ip6tables firewall rules