---

- name: Ensure that varnish is installed
  package:
    name: varnish
    state: present

- name: Ensure varnish is enabled and starts on boot
  systemd:
    name: varnish
    state: started
    enabled: yes

#- name: Write Varnish environment configuration
#  template:
#    src: params.j2
#    dest: /etc/varnish/varnish.params
#    owner: root
#    group: root
#    mode: 0644
#  notify: Restart Varnish
