---

php_vers: 7.2

phpfpm_reserved_mem: "{{ (ansible_memtotal_mb*0.40)|int|abs }}"

#this figure assumes that each PHP process averages 50Mb of RAM.
phpfpm_max_children: "{{ (ansible_memtotal_mb*0.40/50)|round(0,'floor')|int|abs }}"

phpfpm_pools:
  - name: "default"
    process_user: "www-data"
    process_group: "www-data"
    listen: "/var/run/php-fpm/$pool.socket"
    listen_owner: "root"
    listen_group: "www-data"
    listen_mode: "0660"
    log_folder: "/var/log/php-fpm/"
    access_log: "$pool-access.log"
    access_format: '"%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%% %p %P"'
    slowlog: "$pool-slow.log"
    slowlog_timeout: 15
    terminate_timeout: 30
    workers_output: "off"
    log_errors: "on"
    error_log: "$pool-error.log"
    display_errors: "off"
    fastcgi_timeout: 60

phpfpm_default_pool: default

# For when OpCache is installed
phpfpm_opcache_memory_consumption: 128
phpfpm_opcache_interned_strings_buffer: 8
phpfpm_opcache_max_accelerated_files: 4000

php_fpm_ini_options:
  expose_php: "On"
  max_execution_time: 30
  memory_limit: 128M
  realpath_cache_size: 16k
  realpath_cache_ttl: 120
  
php_fpm_composer: false

